import Head from 'next/head';
import style from '@/styles/Home.module.scss';
import Header from '@/components/Header';
import Image from 'next/image';
import { useEffect, useId, useState } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { db } from './../api/firebase-config';

export default function Home() {
  const id = useId();
  const [products, setProducts] = useState<{ id: string }[]>([]);
  const productsCollectionRef = collection(db, 'Products');

  useEffect(() => {
    const getProducts = async () => {
      const data = await getDocs(productsCollectionRef);
      setProducts(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
    };
    getProducts();
  });
  return (
    <>
      <Head>
        <title>Bee Man</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={style.main}>
        <div className={style.home_text_major}>
          <h1>Натуральный мёд</h1>
          <pre>
            Натуральный мёд - это не только Вкусный продукт, но и настоящий
            подарок природы. Это настоящий дар, который приносит в нашу жизнь не
            только вкус и пользу, но и красоту и вдохновение.
          </pre>
        </div>
        <div className={style.home_box_major}>
          <div className={style.home_img_major}>
            <Image
              src="/honeyhome.jpg"
              layout="fill"
              objectFit="cover"
              alt="honey"
            />
          </div>
        </div>
      </main>
      <div className={style.products}>
        <h2>Популярные продукты</h2>
        <div>
          {products.map((product) => {
            return (
              <div key={id}>
                <h3>Name:{product.name}</h3>
                <h3>Price:{product.price}</h3>
                <img src={product.img} />
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}
